comment:
  layout: "header, diff, tree, changes, sunburst"

coverage:
  precision: 3
  round: down
  range: "80...100"

  status:
    project:
      default:
        target: 95%
        threshold: 1%
        base: auto
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        target: 95%
        set_pending: yes
        base: auto
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error

    changes:
      default:
        base: auto
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
